//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007 Openbravo, S.L.
//    http://sourceforge.net/projects/openbravopos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package com.openbravo.pos.customers;

import com.openbravo.basic.BasicException;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.util.UUID;

/**
 *
 * @author  adrianromero
 */
public class CustomersView extends javax.swing.JPanel implements EditorRecord {

    private Object m_oId;
    
    /** Creates new form CustomersView */
    public CustomersView(AppView app, DirtyManager dirty) {
        initComponents();
        
        m_jName.getDocument().addDocumentListener(dirty);
        m_jAddress.getDocument().addDocumentListener(dirty);
        m_jNotes.getDocument().addDocumentListener(dirty);
        m_jVisible.addActionListener(dirty);
        
        writeValueEOF(); 
    }
    
    public void writeValueEOF() {
        m_oId = null;
        m_jName.setText(null);
        m_jAddress.setText(null);
        m_jNotes.setText(null);
        m_jVisible.setSelected(false);
        m_jName.setEnabled(false);
        m_jAddress.setEnabled(false);
        m_jNotes.setEnabled(false);
        m_jVisible.setEnabled(false);
    } 
    
    public void writeValueInsert() {
        m_oId = null;
        m_jName.setText(null);
        m_jAddress.setText(null);
        m_jNotes.setText(null);
        m_jVisible.setSelected(true);
        m_jName.setEnabled(true);
        m_jAddress.setEnabled(true);
        m_jNotes.setEnabled(true);
        m_jVisible.setEnabled(true);
    }

    public void writeValueDelete(Object value) {
        Object[] customer = (Object[]) value;
        m_oId = customer[0];
        m_jName.setText((String) customer[1]);
        m_jAddress.setText((String) customer[2]);
        m_jNotes.setText((String) customer[3]);
        m_jVisible.setSelected(((Boolean) customer[4]).booleanValue());
        m_jName.setEnabled(false);
        m_jAddress.setEnabled(false);
        m_jNotes.setEnabled(false);
        m_jVisible.setEnabled(false);
    }

    public void writeValueEdit(Object value) {
        Object[] customer = (Object[]) value;
        m_oId = customer[0];
        m_jName.setText((String) customer[1]);
        m_jAddress.setText((String) customer[2]);
        m_jNotes.setText((String) customer[3]);
        m_jVisible.setSelected(((Boolean) customer[4]).booleanValue());
        m_jName.setEnabled(true);
        m_jAddress.setEnabled(true);
        m_jNotes.setEnabled(true);
        m_jVisible.setEnabled(true);
    }
    
    public Object createValue() throws BasicException {
        Object[] customer = new Object[5];
        customer[0] = m_oId == null ? UUID.randomUUID().toString() : m_oId;
        customer[1] = m_jName.getText();
        customer[2] = m_jAddress.getText();
        customer[3] = m_jNotes.getText();
        customer[4] = new Boolean(m_jVisible.isSelected());
        return customer;
    }   
    
    public Component getComponent() {
        return this;
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_jNotes = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        m_jAddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        m_jVisible = new javax.swing.JCheckBox();

        setLayout(null);

        jLabel3.setText(AppLocal.getIntString("label.name")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(20, 20, 90, 14);
        add(m_jName);
        m_jName.setBounds(110, 20, 270, 18);

        jLabel12.setText(AppLocal.getIntString("label.notes")); // NOI18N
        add(jLabel12);
        jLabel12.setBounds(20, 130, 90, 14);

        jScrollPane1.setViewportView(m_jNotes);

        add(jScrollPane1);
        jScrollPane1.setBounds(110, 130, 270, 70);

        jLabel13.setText(AppLocal.getIntString("label.address")); // NOI18N
        add(jLabel13);
        jLabel13.setBounds(20, 50, 90, 14);

        jScrollPane2.setViewportView(m_jAddress);

        add(jScrollPane2);
        jScrollPane2.setBounds(110, 50, 270, 70);

        jLabel4.setText(AppLocal.getIntString("label.visible")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(20, 210, 90, 14);
        add(m_jVisible);
        m_jVisible.setBounds(110, 210, 140, 20);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea m_jAddress;
    private javax.swing.JTextField m_jName;
    private javax.swing.JTextArea m_jNotes;
    private javax.swing.JCheckBox m_jVisible;
    // End of variables declaration//GEN-END:variables
    
}
