/*
 * JCompany.java
 *
 * Created on 25 de Fevereiro de 2010, 23:36
 */
package com.openbravo.pos.panels;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JPanel;

public class JCompany extends JPanel implements JPanelView, BeanFactoryApp {

    private AppView m_App;
    private int lines = 0;
    
    /** Creates new form JCompany */
    public JCompany() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        CompanyName = new javax.swing.JLabel();
        AddressDetail = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        jTextCompanyName = new javax.swing.JTextField();
        PostalCode = new javax.swing.JLabel();
        Country = new javax.swing.JLabel();
        jTextAddressDetail = new javax.swing.JTextField();
        jTextCity = new javax.swing.JTextField();
        jTextPostalCode = new javax.swing.JTextField();
        jTextCountry = new javax.swing.JTextField();
        jTextTelephone = new javax.swing.JTextField();
        Telephone = new javax.swing.JLabel();
        jTextFax = new javax.swing.JTextField();
        Fax = new javax.swing.JLabel();
        TaxRegistrationNumber = new javax.swing.JLabel();
        jTextTaxRegistrationNumber = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        CompanyID = new javax.swing.JLabel();
        jTextCompanyID = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        BuildingNumber = new javax.swing.JLabel();
        jTextBuildingNumber = new javax.swing.JTextField();
        Region = new javax.swing.JLabel();
        jTextRegion = new javax.swing.JTextField();
        BusinessName = new javax.swing.JLabel();
        jTextBusinessName = new javax.swing.JTextField();

        jPanelHeader.setEnabled(false);

        CompanyName.setLabelFor(CompanyName);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        CompanyName.setText(bundle.getString("label.companyname")); // NOI18N

        AddressDetail.setLabelFor(AddressDetail);
        AddressDetail.setText(bundle.getString("label.companyadressdetail")); // NOI18N

        City.setLabelFor(City);
        City.setText(bundle.getString("label.companycity")); // NOI18N

        PostalCode.setLabelFor(PostalCode);
        PostalCode.setText(bundle.getString("label.companypostalcode")); // NOI18N

        Country.setLabelFor(Country);
        Country.setText(bundle.getString("label.companycountry")); // NOI18N

        Telephone.setLabelFor(Telephone);
        Telephone.setText(bundle.getString("label.companyphone")); // NOI18N

        Fax.setLabelFor(Fax);
        Fax.setText(bundle.getString("label.companyfax")); // NOI18N

        TaxRegistrationNumber.setLabelFor(TaxRegistrationNumber);
        TaxRegistrationNumber.setText(bundle.getString("label.companytaxregnumber")); // NOI18N

        jButtonSubmit.setText(bundle.getString("button.companysave")); // NOI18N
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        CompanyID.setLabelFor(CompanyID);
        CompanyID.setText(bundle.getString("label.companyid")); // NOI18N

        Email.setLabelFor(Email);
        Email.setText(bundle.getString("label.companyemail")); // NOI18N

        BuildingNumber.setLabelFor(BuildingNumber);
        BuildingNumber.setText(bundle.getString("label.companybuildingnumber")); // NOI18N

        Region.setLabelFor(Region);
        Region.setText(bundle.getString("label.companyregion")); // NOI18N

        BusinessName.setLabelFor(BusinessName);
        BusinessName.setText(bundle.getString("label.companybusinessname")); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaxRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTaxRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAddressDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBuildingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSubmit))
                        .addGap(156, 156, 156))
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuildingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTaxRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAddressDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuildingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBuildingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try {        
        
            lines = DataBaseAccess.Count(m_App, "SELECT COUNT(companyID) FROM HEADER");
                    
            if (lines == 0) {
                Company.insertHeader(m_App, getPanel());
            } else {
                Company.updateHeader(m_App, getPanel());
            }
        } catch (BasicException ex) {
            Logger.getLogger(JCompany.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JCompany.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private ArrayList getPanel() {

        ArrayList headerAL = new ArrayList();

        headerAL.add(jTextCompanyID.getText());
        headerAL.add(jTextTaxRegistrationNumber.getText());
        headerAL.add(jTextCompanyName.getText());
        headerAL.add(jTextBusinessName.getText());
        headerAL.add(jTextAddressDetail.getText());
        headerAL.add(jTextBuildingNumber.getText());
        headerAL.add(jTextCity.getText());
        headerAL.add(jTextPostalCode.getText());
        headerAL.add(jTextRegion.getText());
        headerAL.add(jTextCountry.getText());
        headerAL.add(jTextTelephone.getText());
        headerAL.add(jTextFax.getText());
        headerAL.add(jTextEmail.getText());
        
        return headerAL;
    }

    private void setPainel(ResultSet painelRS) throws SQLException {

        painelRS.next();
        jTextCompanyID.setText(painelRS.getString("companyID"));
        jTextTaxRegistrationNumber.setText(painelRS.getString("taxRegistrationNumber"));
        jTextCompanyName.setText(painelRS.getString("companyName"));
        jTextBusinessName.setText(painelRS.getString("businessName"));
        jTextAddressDetail.setText(painelRS.getString("addressDetail"));
        jTextBuildingNumber.setText(painelRS.getString("buildingNumber"));
        jTextCity.setText(painelRS.getString("city"));
        jTextPostalCode.setText(painelRS.getString("postalCode"));
        jTextRegion.setText(painelRS.getString("region"));
        jTextCountry.setText(painelRS.getString("country"));
        jTextTelephone.setText(painelRS.getString("telephone"));
        jTextFax.setText(painelRS.getString("fax"));
        jTextEmail.setText(painelRS.getString("email"));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressDetail;
    private javax.swing.JLabel BuildingNumber;
    private javax.swing.JLabel BusinessName;
    private javax.swing.JLabel City;
    private javax.swing.JLabel CompanyID;
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel Country;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fax;
    private javax.swing.JLabel PostalCode;
    private javax.swing.JLabel Region;
    private javax.swing.JLabel TaxRegistrationNumber;
    private javax.swing.JLabel Telephone;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jTextAddressDetail;
    private javax.swing.JTextField jTextBuildingNumber;
    private javax.swing.JTextField jTextBusinessName;
    private javax.swing.JTextField jTextCity;
    private javax.swing.JTextField jTextCompanyID;
    private javax.swing.JTextField jTextCompanyName;
    private javax.swing.JTextField jTextCountry;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextPostalCode;
    private javax.swing.JTextField jTextRegion;
    private javax.swing.JTextField jTextTaxRegistrationNumber;
    private javax.swing.JTextField jTextTelephone;
    // End of variables declaration//GEN-END:variables
    public String getTitle() {
        return AppLocal.getIntString("Menu.Company");
    }

    public void activate()
            throws BasicException {
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    public void init(AppView app)
            throws BeanFactoryException {
        try {

            m_App = app;

            lines = DataBaseAccess.Count(m_App, "SELECT COUNT(companyID) FROM HEADER");
            if (lines > 0) {
                setPainel(DataBaseAccess.Select(m_App, "SELECT * FROM HEADER"));
            }
        } catch (BasicException ex) {
            Logger.getLogger(JCompany.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JCompany.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Object getBean() {
        return this;
    }
}
