//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2008 Open Sistemas de Información Internet, S.L.
//    http://www.opensistemas.com
//    http://sourceforge.net/projects/openbravopos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package com.openbravo.pos.inventory;

import java.awt.Component;
import java.util.UUID;
import javax.swing.*;

import com.openbravo.pos.forms.AppLocal;
import com.openbravo.format.Formats;
import com.openbravo.basic.BasicException;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.data.user.DirtyManager;

/**
 *
 * @author  Luis Ig. Bacas Riveiro	lbacas@opensistemas.com
 * @author  Pablo J. Urbano Santos	purbano@opensistemas.com
 */
public class UnitsMeasureEditor extends JPanel implements EditorRecord {
    
    private Object m_oId;
    private DirtyManager m_dirty;
    
    /** Creates new form DiscountEditor */
    public UnitsMeasureEditor(DirtyManager dirty) {
        initComponents();

        m_dirty = dirty;
        m_jName.getDocument().addDocumentListener(dirty);
        m_jSymbol.getDocument().addDocumentListener(dirty);
        
        writeValueEOF();
    }
    
    public void writeValueEOF() {
        m_oId = null;
        m_jName.setText(null);
        m_jSymbol.setText(null);
        
        m_jName.setEnabled(false);
        m_jSymbol.setEnabled(false);
    }
    
    public void writeValueInsert() {
        m_oId = null;
        m_jName.setText(null);
        m_jSymbol.setText(null);
        
        m_jName.setEnabled(true);
        m_jSymbol.setEnabled(true);
    }
    
    public void writeValueDelete(Object value) {

        Object[] discount = (Object[]) value;
        m_oId = discount[0];
        m_jName.setText(Formats.STRING.formatValue(discount[1]));
        m_jSymbol.setText(Formats.STRING.formatValue(discount[2]));
        
        m_jName.setEnabled(false);
        m_jSymbol.setEnabled(false);
    }    
    
    public void writeValueEdit(Object value) {

        Object[] discount = (Object[]) value;
        m_oId = discount[0];
        m_jName.setText(Formats.STRING.formatValue(discount[1]));
        m_jSymbol.setText(Formats.STRING.formatValue(discount[2]));
        
        m_jName.setEnabled(true);
        m_jSymbol.setEnabled(true);
        m_dirty.setDirty(false);
    }

    public Object createValue() throws BasicException {
        Object[] discount = new Object[5];

        discount[0] = m_oId == null ? UUID.randomUUID().toString() : m_oId;
        discount[1] = m_jName.getText();
        discount[2] = m_jSymbol.getText();
        
        return discount;
    }    
     
    public Component getComponent() {
        return this;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_jSymbol = new javax.swing.JTextField();

        setLayout(null);
        add(m_jName);
        m_jName.setBounds(100, 20, 200, 20);

        jLabel2.setText(AppLocal.getIntString("Label.Name")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 17);

        jLabel3.setText(AppLocal.getIntString("label.symbol")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(20, 50, 80, 17);
        add(m_jSymbol);
        m_jSymbol.setBounds(100, 50, 60, 20);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField m_jName;
    private javax.swing.JTextField m_jSymbol;
    // End of variables declaration//GEN-END:variables
    
}
