//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.payment;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.format.Formats;
import com.openbravo.pos.customers.CustomerInfoExt;
import com.openbravo.pos.util.RoundUtils;
//Botão data
import java.util.Date;
import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;

import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.pos.mant.BankInfo;


public class JPaymentCheque extends javax.swing.JPanel implements JPaymentInterface {
    
    private JPaymentNotifier m_notifier;

    private double m_dPaid;
    private double m_dTotal;

    private ComboBoxValModel m_BankModel;
    private SentenceList m_sentbank;
    private DataLogicSales  m_dlSales;
   
    /** Creates new form JPaymentCash */
    public JPaymentCheque(JPaymentNotifier notifier, DataLogicSales dlSales) {
        
        m_notifier = notifier;

        initComponents();  
        
        m_jTendered.addPropertyChangeListener("Edition", new RecalculateState());
        m_jTendered.addEditorKeys(m_jKeys);
        m_jChequeNumberBox.addPropertyChangeListener("Edition", new RecalculateState());
        m_jChequeNumberBox.addEditorKeys(m_jKeys);

        // MSL

        DataLogicSales m_dlSales = null;
        m_dlSales = dlSales;

        m_sentbank = m_dlSales.getBanksList();
        m_BankModel = new ComboBoxValModel();

    }
    
    public void activate(CustomerInfoExt customerext, double dTotal, String transID) {

        m_dTotal = dTotal;
        m_jTendered.reset();
        m_jTendered.activate();
        m_jChequeNumberBox.reset();
        

        // MSL
        try {
            m_BankModel = new ComboBoxValModel(m_sentbank.list());
            jBankNameCombo.setModel(m_BankModel);
            String bank = ((BankInfo) m_BankModel.getElementAt(0)).getName();
        } catch (BasicException e) {
            
        }
        




        printState();
        
    }
    //Adicionar campos ao pagamento por cheque
    public PaymentInfo executePayment() {
        return new PaymentInfoTicket(m_jChequeDate.getText(), jBankNameCombo.getSelectedItem(), m_jChequeNumberBox.getText(), m_dPaid, "cheque");
    }
    public Component getComponent() {
        return this;
    }

    private void printState() {
        
        Double value = m_jTendered.getDoubleValue();
        if (value == null) {
            m_dPaid = m_dTotal;
        } else {
            m_dPaid = value;
        } 

        m_jMoneyEuros.setText(Formats.CURRENCY.formatValue(new Double(m_dPaid)));
        
        int iCompare = RoundUtils.compare(m_dPaid, m_dTotal);
        
        // if iCompare > 0 then the payment is not valid
        m_notifier.setStatus(m_dPaid > 0.0 && iCompare <= 0, iCompare == 0);
    }
    
    private class RecalculateState implements PropertyChangeListener {
        public void propertyChange(PropertyChangeEvent evt) {
            printState();
        }
    }     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        m_jKeys = new com.openbravo.editor.JEditorKeys();
        jPanel3 = new javax.swing.JPanel();
        m_jTendered = new com.openbravo.editor.JEditorCurrencyPositive();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        m_jMoneyEuros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        m_jChequeDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        m_jbtndate = new javax.swing.JButton();
        m_jChequeNumberBox = new com.openbravo.editor.JEditorStringNumber();
        jBankNameCombo = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(m_jKeys);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(m_jTendered, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel2.add(jPanel1, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(null);

        jLabel8.setText(AppLocal.getIntString("Label.InputCash")); // NOI18N
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 20, 120, 25);

        m_jMoneyEuros.setBackground(new java.awt.Color(153, 153, 255));
        m_jMoneyEuros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        m_jMoneyEuros.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")), javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4)));
        m_jMoneyEuros.setOpaque(true);
        m_jMoneyEuros.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel4.add(m_jMoneyEuros);
        m_jMoneyEuros.setBounds(140, 20, 150, 25);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        jLabel1.setText(bundle.getString("label.chequenumber")); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 50, 120, 25);

        jLabel2.setText(bundle.getString("label.bankname")); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 80, 120, 25);
        jPanel4.add(m_jChequeDate);
        m_jChequeDate.setBounds(140, 110, 100, 25);

        jLabel3.setText(bundle.getString("label.chequedate")); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 110, 120, 25);

        m_jbtndate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        m_jbtndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jbtndateActionPerformed(evt);
            }
        });
        jPanel4.add(m_jbtndate);
        m_jbtndate.setBounds(250, 110, 40, 25);
        jPanel4.add(m_jChequeNumberBox);
        m_jChequeNumberBox.setBounds(140, 50, 180, 25);

        jBankNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBankNameComboActionPerformed(evt);
            }
        });
        jPanel4.add(jBankNameCombo);
        jBankNameCombo.setBounds(140, 80, 150, 25);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void m_jbtndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jbtndateActionPerformed

        Date date;
        try {
            date = (Date) Formats.DATE.parseValue(m_jChequeDate.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendar(this, date);
        if (date != null) {
            m_jChequeDate.setText(Formats.DATE.formatValue(date));
        }
}//GEN-LAST:event_m_jbtndateActionPerformed

    private void jBankNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBankNameComboActionPerformed
        // TODO add your handling code here:
        // MSL
        String bank = ((BankInfo) m_BankModel.getSelectedItem()).getName();
    }//GEN-LAST:event_jBankNameComboActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jBankNameCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField m_jChequeDate;
    private com.openbravo.editor.JEditorStringNumber m_jChequeNumberBox;
    private com.openbravo.editor.JEditorKeys m_jKeys;
    private javax.swing.JLabel m_jMoneyEuros;
    private com.openbravo.editor.JEditorCurrencyPositive m_jTendered;
    private javax.swing.JButton m_jbtndate;
    // End of variables declaration//GEN-END:variables
    
}
