//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2008 Open Sistemas de Información Internet, S.L.
//    http://www.opensistemas.com
//    http://sourceforge.net/projects/openbravopos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package com.openbravo.pos.mant;

import java.awt.Component;
import java.util.UUID;
import javax.swing.*;

import com.openbravo.pos.forms.AppLocal;
import com.openbravo.format.Formats;
import com.openbravo.basic.BasicException;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.data.user.DirtyManager;

/**
 *
 * @author  Helder Teixeira	hept@netc.pt
 * Created on April, 2010
 */
public class BankEditor extends JPanel implements EditorRecord {
    
    private String m_sID;
    private DirtyManager m_dirty;
    
    public BankEditor(DirtyManager dirty) {
        initComponents();

        m_dirty = dirty;
        m_jName.getDocument().addDocumentListener(dirty);
        m_jCode.getDocument().addDocumentListener(dirty);
        
        writeValueEOF();
    }
    
    public void writeValueEOF() {
        m_sID = null;
        m_jName.setText(null);
        m_jCode.setText(null);
        
        m_jName.setEnabled(false);
        m_jCode.setEnabled(false);
    }
    
    public void writeValueInsert() {
        m_sID = UUID.randomUUID().toString();
        m_jName.setText(null);
        m_jCode.setText(null);
        
        m_jName.setEnabled(true);
        m_jCode.setEnabled(true);
    }
    
    public void writeValueDelete(Object value) {

        Object[] bank = (Object[]) value;
        m_sID = Formats.STRING.formatValue(bank[0]);
        m_jName.setText(Formats.STRING.formatValue(bank[1]));
        m_jCode.setText(Formats.STRING.formatValue(bank[2]));
        
        m_jName.setEnabled(false);
        m_jCode.setEnabled(false);
    }    
    
    public void writeValueEdit(Object value) {

        Object[] bank = (Object[]) value;
        m_sID = Formats.STRING.formatValue(bank[0]);
        m_jName.setText(Formats.STRING.formatValue(bank[1]));
        m_jCode.setText(Formats.STRING.formatValue(bank[2]));
        
        m_jName.setEnabled(true);
        m_jCode.setEnabled(true);
        m_dirty.setDirty(false);
    }

    public Object createValue() throws BasicException {
        Object[] bank = new Object[3];

        bank[0] = m_sID;
        bank[1] = m_jName.getText();
        bank[2] = m_jCode.getText();
        
        return bank;
    }    
     
    public Component getComponent() {
        return this;
    }
    
    public void refresh() {
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_jCode = new javax.swing.JTextField();

        setLayout(null);
        add(m_jName);
        m_jName.setBounds(100, 20, 200, 25);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        jLabel2.setText(bundle.getString("bank.name")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 25);

        jLabel3.setText(bundle.getString("bank.code")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(20, 50, 80, 25);
        add(m_jCode);
        m_jCode.setBounds(100, 50, 60, 25);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField m_jCode;
    private javax.swing.JTextField m_jName;
    // End of variables declaration//GEN-END:variables

    
}
